linters-settings:
  errcheck:
    # 以下の関数のエラーチェック漏れを無視
    exclude-functions:
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Sprint
      - fmt.Sprintf
      - fmt.Sprintln
      - (*os.File).Close

linters:
  disable-all: true
  enable:
    - errcheck
    - govet

run:
  timeout: 5m
  tests: true
  
issues:
  exclude-rules:
    # テストファイルでのエラーチェック漏れを無視
    - path: _test\.go
      linters:
        - errcheck
      text: "Error return value of"